name: Publish to GitHub Packages

on:
  push:
    branches:
      - main  # Hoặc branch bạn muốn publish

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
          scope: 'quoioln'  # Thay bằng username của bạn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # - name: Build package
      #   run: yarn build  # Nếu cần build

      - name: Publish to GitHub Packages
        run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
